### ISSUE TITLE
[Issue]: Product-name information missing for MI300 GPUs in AKS

### ISSUE THREAD

**Issue by lalitmsft** [ROCm/k8s-device-plugin#112]
### Problem Description

We are using AMD MI300X GPUs in AKS. We use the node-labeller Daemonset to discover the product-name however on this [amdgpu-labeller](https://github.com/ROCm/k8s-device-plugin/blob/master/k8s-ds-amdgpu-labeller.yaml). 

Args passed to the container.
```yaml
    - -vram
    - -cu-count
    - -simd-count
    - -device-id
    - -family
    - -product-name
    - -driver-version
    - -driver-src-version
    - -firmware
```
SKU of the node `Standard_ND96isr_MI300X_v5`
Label added by AMD on the node.
```yaml
    amd.com/gpu.cu-count: "304"
    amd.com/gpu.device-id: 74b5
    amd.com/gpu.driver-src-version: 0A82C3819E55873715679EA
    amd.com/gpu.driver-version: 6.8.5
    amd.com/gpu.family: AI
    amd.com/gpu.simd-count: "1216"
    amd.com/gpu.vram: 191G
    beta.amd.com/gpu.cu-count: "304"
    beta.amd.com/gpu.cu-count.304: "8"
    beta.amd.com/gpu.device-id: 74b5
    beta.amd.com/gpu.device-id.74b5: "8"
    beta.amd.com/gpu.family: AI
    beta.amd.com/gpu.family.AI: "8"
    beta.amd.com/gpu.firmware.CE.feat.0: "8"
    beta.amd.com/gpu.firmware.CE.fw.0: "8"
    beta.amd.com/gpu.firmware.MC.feat.0: "8"
    beta.amd.com/gpu.firmware.MC.fw.0: "8"
    beta.amd.com/gpu.firmware.ME.feat.0: "8"
    beta.amd.com/gpu.firmware.ME.fw.0: "8"
    beta.amd.com/gpu.firmware.MEC.feat.49: "8"
    beta.amd.com/gpu.firmware.MEC.fw.160: "8"
    beta.amd.com/gpu.firmware.PFP.feat.0: "8"
    beta.amd.com/gpu.firmware.PFP.fw.0: "8"
    beta.amd.com/gpu.firmware.RLC.feat.1: "8"
    beta.amd.com/gpu.firmware.RLC.fw.64: "8"
    beta.amd.com/gpu.firmware.SDMA0.feat.44: "8"
    beta.amd.com/gpu.firmware.SDMA0.fw.21: "8"
    beta.amd.com/gpu.firmware.SMC.feat.0: "8"
    beta.amd.com/gpu.firmware.SMC.fw.5600514: "8"
    beta.amd.com/gpu.firmware.UVD.feat.0: "8"
    beta.amd.com/gpu.firmware.UVD.fw.0: "8"
    beta.amd.com/gpu.firmware.VCE.feat.0: "8"
    beta.amd.com/gpu.firmware.VCE.fw.0: "8"
    beta.amd.com/gpu.simd-count: "1216"
    beta.amd.com/gpu.simd-count.1216: "8"
    beta.amd.com/gpu.vram: 191G
    beta.amd.com/gpu.vram.191G: "8"
```

This is from a different SKU in azure `Standard_nd96asr_mi200_v4`
```
amd.com/gpu.cu-count: "110"
    amd.com/gpu.device-id: 740c
    amd.com/gpu.driver-src-version: 0A82C3819E55873715679EA
    amd.com/gpu.driver-version: 6.8.5
    amd.com/gpu.family: AI
    amd.com/gpu.product-name: AMD_INSTINCT_MI250X_MCM_OAM_AC_MBA_MSFT
    amd.com/gpu.simd-count: "440"
    amd.com/gpu.vram: 64G
    beta.amd.com/gpu.cu-count: "110"
    beta.amd.com/gpu.cu-count.110: "16"
    beta.amd.com/gpu.device-id: 740c
    beta.amd.com/gpu.device-id.740c: "16"
    beta.amd.com/gpu.family: AI
    beta.amd.com/gpu.family.AI: "16"
    beta.amd.com/gpu.firmware.CE.feat.0: "16"
    beta.amd.com/gpu.firmware.CE.fw.0: "16"
    beta.amd.com/gpu.firmware.MC.feat.0: "16"
    beta.amd.com/gpu.firmware.MC.fw.0: "16"
    beta.amd.com/gpu.firmware.ME.feat.0: "16"
    beta.amd.com/gpu.firmware.ME.fw.0: "16"
    beta.amd.com/gpu.firmware.MEC.feat.46: "16"
    beta.amd.com/gpu.firmware.MEC.fw.83: "16"
    beta.amd.com/gpu.firmware.PFP.feat.0: "16"
    beta.amd.com/gpu.firmware.PFP.fw.0: "16"
    beta.amd.com/gpu.firmware.RLC.feat.1: "16"
    beta.amd.com/gpu.firmware.RLC.fw.17: "16"
    beta.amd.com/gpu.firmware.SDMA0.feat.44: "16"
    beta.amd.com/gpu.firmware.SDMA0.fw.8: "16"
    beta.amd.com/gpu.firmware.SMC.feat.0: "16"
    beta.amd.com/gpu.firmware.SMC.fw.4471808: "16"
    beta.amd.com/gpu.firmware.UVD.feat.0: "16"
    beta.amd.com/gpu.firmware.UVD.fw.0: "16"
    beta.amd.com/gpu.firmware.VCE.feat.0: "16"
    beta.amd.com/gpu.firmware.VCE.fw.0: "16"
    beta.amd.com/gpu.product-name: AMD_INSTINCT_MI250X_MCM_OAM_AC_MBA_MSFT
    beta.amd.com/gpu.product-name.AMD_INSTINCT_MI250X_MCM_OAM_AC_MBA_MSFT: "16"
    beta.amd.com/gpu.simd-count: "440"
    beta.amd.com/gpu.simd-count.440: "16"
    beta.amd.com/gpu.vram: 64G
    beta.amd.com/gpu.vram.64G: "16"
```

When I use `rocm-smi --showproductname` it works on both GPUs (MI200 and MI300x).
Output on MI300.
```
GPU[0]          : Card Series:          Aqua Vanjaram [Instinct MI300X VF]
GPU[0]          : Card Model:           0x74b5
GPU[0]          : Card Vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[0]          : Card SKU:             M3000100
GPU[0]          : Subsystem ID:         0x74a1
GPU[0]          : Device Rev:           0x00
GPU[0]          : Node ID:              2
GPU[0]          : GUID:                 65402
GPU[0]          : GFX Version:          gfx942
```

On MI200
```
GPU[0]          : Card Series:          AMD INSTINCT MI250X (MCM) OAM AC MBA MSFT
GPU[0]          : Card Model:           0x740c
GPU[0]          : Card Vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[0]          : Card SKU:             D65205
GPU[0]          : Subsystem ID:         0x0b0c
GPU[0]          : Device Rev:           0x01
GPU[0]          : Node ID:              4
GPU[0]          : GUID:                 10595
GPU[0]          : GFX Version:          gfx9010
```

The expectation is that product-name should be available on all GPUs, both MI200 and MI300

### Operating System

NAME="Ubuntu" VERSION="22.04.5 LTS (Jammy Jellyfish)"

### CPU

model name : Intel(R) Xeon(R) Platinum 8480C

### GPU

Name: Intel(R) Xeon(R) Platinum 8480C Marketing Name: Intel(R) Xeon(R) Platinum 8480C Name: Intel(R) Xeon(R) Platinum 8480C Marketing Name: Intel(R) Xeon(R) Platinum 8480C Name: gfx942 Marketing Name: AMD Instinct MI300X VF Name: amdgcn-amd-amdhsa--gfx942:sramecc+:xnack- Name: gfx942 Marketing Name: AMD Instinct MI300X VF Name: amdgcn-amd-amdhsa--gfx942:sramecc+:xnack- Name: gfx942 Marketing Name: AMD Instinct MI300X VF Name: amdgcn-amd-amdhsa--gfx942:sramecc+:xnack- Name: gfx942 Marketing Name: AMD Instinct MI300X VF Name: amdgcn-amd-amdhsa--gfx942:sramecc+:xnack- Name: gfx942 Marketing Name: AMD Instinct MI300X VF Name: amdgcn-amd-amdhsa--gfx942:sramecc+:xnack- Name: gfx942 Marketing Name: AMD Instinct MI300X VF Name: amdgcn-amd-amdhsa--gfx942:sramecc+:xnack- Name: gfx942 Marketing Name: AMD Instinct MI300X VF Name: amdgcn-amd-amdhsa--gfx942:sramecc+:xnack- Name: gfx942 Marketing Name: AMD Instinct MI300X VF Name: amdgcn-amd-amdhsa--gfx942:sramecc+:xnack-

### ROCm Version

6.2.60204-1
