### ISSUE TITLE
[Feature]: Sharing GPUs among all containers of a K8s pod

### ISSUE THREAD

**Issue by yx-lamini** [ROCm/k8s-device-plugin#69]
### Suggestion Description

`main-container` requests GPU, `rocm-smi-exporter-sidecar` is another container of the pod; we'd 
```
apiVersion: v1
kind: Pod
metadata:
  name: {{ pod-name }}
  labels:
    exporter: rocm-smi
spec:
  containers:
  - name: main-container
    image: main-container-imamge:v1
    resources:
      limits:
        amd.com/gpu: {{ count }}
  # Add the following sidecar container to your pod
  - name: rocm-smi-exporter-sidecar
    image: rocm-smi-exporter
    args: ["lrocm-smi-exporter", "--port=9001"]
    imagePullPolicy: Always
    ports:
    - containerPort: 9001
      name: prometheus
```
