### ISSUE TITLE
[Issue]: Run ROCm containers as non-root, unprivileged user

### ISSUE THREAD

**Issue by hmoazzem** [ROCm/k8s-device-plugin#93]
### Problem Description

Below example rocm-pytorch Deployment with `securityContext: {runAsUser: 0, privileged: true}` detects host GPU.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rocm-pytorch
  name: rocm-pytorch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocm-pytorch
  template:
    metadata:
      labels:
        app: rocm-pytorch
    spec:
      containers:
      - image: docker.io/rocm/pytorch:latest
        name: pytorch
        command:
        - /bin/sh
        - -c
        - |
          python3 -c "import torch; print(torch.cuda.is_available());"
          sleep infinity
        securityContext:
          runAsUser: 0
          privileged: true
#          privileged: false
#          runAsUser: 1000
#          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /dev/dri
          name: dev-dri
        - mountPath: /dev/kfd
          name: dev-kfd
      volumes:
      - name: dev-dri
        hostPath:
          path: /dev/dri
          type: Directory
      - name: dev-kfd
        hostPath:
          path: /dev/kfd
          type: CharDevice
```

Is it possible to run the container as a non-root, unprivileged user (as the commented out securityContext above)?

### Operating System

RHEL9.5

### CPU

AMD Ryzen 9 7950X

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.3.0

### ROCm Component

ROCK-Kernel-Driver

### Steps to Reproduce

Ensure the the pod is assigned to a GPU node. I'm using k3s on a single node (kvm VM with a GPU passed-through to it)  cluster.
